chore: add yarn.lock to .gitignore
hedgedoc/markdown-it-better-task-lists pull request #79
Opened 2022-01-31 18:57 UTC by DerMolly

### Description
This PR add yarn.lock to the .gitignore file

### Steps

- [x] Added changes
- [x] I read the [contribution documentation](https://github.com/hedgedoc/markdown-it-better-task-lists/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2022-01-31 19:22 UTC, mrdrogdrog requested changes
If you ignore it then remove it from the git.

2022-01-31 20:54 UTC, DerMolly commented
> If you ignore it then remove it from the git.

It's not in the repo?

2022-02-01 08:16 UTC, ErikMichelson commented
Why do you want to exclude the lockfile?

2022-02-01 08:25 UTC, mrdrogdrog commented
We don't use pinned dependencies here because it's a lib. So why should we commit the lock?

2022-02-01 11:23 UTC, ErikMichelson commented
Well okay, go for it. But then, I'd include `package-lock.json` as well.

2022-07-02 12:02 UTC, mrdrogdrog commented
Done in https://github.com/hedgedoc/markdown-it-better-task-lists/pull/90

2022-07-02 12:03 UTC, closed without merging